const fs = require("fs");
const path = require("path");
const { existingWikiPages, newTreks } = require("./trekCatalogSource");

const sql = fs.readFileSync(path.join(__dirname, "seed_treks.sql"), "utf8");
const existing = [...sql.matchAll(/\('((?:[^']|'')+)',\s*([\d.]+),\s*([\d.]+)\)/g)].map((match) => ({
  title: match[1].replace(/''/g, "'"), price: Number(match[2]), commission: Number(match[3]),
}));
if (existing.length !== existingWikiPages.length) throw new Error(`Expected ${existingWikiPages.length} existing treks, found ${existing.length}`);

const catalog = [
  ...existing.map((trek, index) => ({ ...trek, wikiPage: existingWikiPages[index] })),
  ...newTreks.map(([title, price, wikiPage]) => ({ title, price, commission: Number((price * 0.008).toFixed(2)), wikiPage })),
];
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function fetchBatch(items) {
  const params = new URLSearchParams({
    action: "query", format: "json", formatversion: "2", redirects: "1",
    prop: "pageimages", piprop: "thumbnail", pithumbsize: "640",
    titles: items.map((item) => item.wikiPage).join("|"),
  });
  let response;
  for (let attempt = 0; attempt < 4; attempt += 1) {
    response = await fetch(`https://en.wikipedia.org/w/api.php?${params}`, { headers: { "User-Agent": "TravelLeadersCatalog/1.0" } });
    if (response.ok) break;
    if (response.status !== 429 && response.status < 500) throw new Error(`Wikipedia returned ${response.status}`);
    await sleep(1500 * (attempt + 1));
  }
  if (!response?.ok) throw new Error(`Wikipedia returned ${response?.status || "no response"}`);

  const data = await response.json();
  const aliases = new Map();
  for (const item of data.query?.normalized || []) aliases.set(item.from, item.to);
  for (const item of data.query?.redirects || []) aliases.set(item.from, item.to);
  const pages = new Map((data.query?.pages || []).map((page) => [page.title, page]));

  return items.map((item) => {
    let resolvedTitle = item.wikiPage;
    for (let step = 0; step < 4 && aliases.has(resolvedTitle); step += 1) resolvedTitle = aliases.get(resolvedTitle);
    const page = pages.get(resolvedTitle);
    const imageUrl = page?.thumbnail?.source;
    if (!imageUrl || /\.svg(?:\.png)?(?:$|\?)/i.test(imageUrl)) throw new Error(`${item.wikiPage}: no suitable location photo found`);
    return {
      title: item.title, price: item.price, commission: item.commission, imageUrl,
      imageSource: `https://en.wikipedia.org/wiki/${encodeURIComponent(page.title.replaceAll(" ", "_"))}`,
    };
  });
}

async function main() {
  const completed = [];
  for (let index = 0; index < catalog.length; index += 40) {
    completed.push(...(await fetchBatch(catalog.slice(index, index + 40))));
    console.log(`Resolved ${completed.length}/${catalog.length} location photos`);
    await sleep(1000);
  }
  const output = `// Generated by db/build_trek_catalog.js.\nmodule.exports = ${JSON.stringify(completed, null, 2)};\n`;
  fs.writeFileSync(path.join(__dirname, "trekCatalog.js"), output, "utf8");
  console.log(`Wrote ${completed.length} curated treks to db/trekCatalog.js`);
}

main().catch((error) => { console.error(error.message); process.exitCode = 1; });
