// Generated by db/build_trek_catalog.js.
module.exports = [
  {
    "title": "San Francisco Golden Gate Bridge Glow",
    "price": 88,
    "commission": 0.7,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Golden_Gate_Bridge_as_seen_from_Battery_East.jpg/960px-Golden_Gate_Bridge_as_seen_from_Battery_East.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Golden_Gate_Bridge"
  },
  {
    "title": "Maldives Coral Atoll Tranquility",
    "price": 78,
    "commission": 0.62,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/44/Rehendi_Suite_Deck_%28Service%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Tourism_in_the_Maldives"
  },
  {
    "title": "Cappadocia Midnight Balloon Serenity",
    "price": 64,
    "commission": 0.51,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Cappadocia_balloon_trip%2C_Ortahisar_Castle_%2811893715185%29.jpg/960px-Cappadocia_balloon_trip%2C_Ortahisar_Castle_%2811893715185%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Cappadocia"
  },
  {
    "title": "Tokyo Neon Metropolis Dreams",
    "price": 92,
    "commission": 0.74,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Shibuya_Crossing%2C_Aerial.jpg/960px-Shibuya_Crossing%2C_Aerial.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Shibuya_Crossing"
  },
  {
    "title": "Banff National Park Wilderness River Rapids",
    "price": 57,
    "commission": 0.46,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Moraine_Lake_17092005.jpg/960px-Moraine_Lake_17092005.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Banff_National_Park"
  },
  {
    "title": "Seychelles Azure Archipelago Escape",
    "price": 70,
    "commission": 0.56,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Luftbild_Insel_La_Digue_Seychellen.DNG_%2839617026111%29.jpg/960px-Luftbild_Insel_La_Digue_Seychellen.DNG_%2839617026111%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/La_Digue"
  },
  {
    "title": "Swiss Alps Alpine Valley Vista",
    "price": 88,
    "commission": 0.7,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/7/77/BerneseAlps.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Bernese_Alps"
  },
  {
    "title": "Black Forest Enchanted Woodland Path",
    "price": 68,
    "commission": 0.54,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Blick_vom_Hohfelsen.jpg/960px-Blick_vom_Hohfelsen.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Black_Forest"
  },
  {
    "title": "Plitvice Lakes Emerald Lagoon Retreat",
    "price": 72,
    "commission": 0.58,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/View_in_Plitvice_Lakes_National_Park.jpg/960px-View_in_Plitvice_Lakes_National_Park.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Plitvice_Lakes_National_Park"
  },
  {
    "title": "Venice Sunset Gondola Reverie",
    "price": 60,
    "commission": 0.48,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Venezia_aerial_view.jpg/960px-Venezia_aerial_view.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Venice"
  },
  {
    "title": "Iceland Skógafoss Majestic Falls Cascade",
    "price": 60,
    "commission": 0.48,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/2008-05-24_35_Sk%C3%B3gafoss.jpg/960px-2008-05-24_35_Sk%C3%B3gafoss.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Sk%C3%B3gafoss"
  },
  {
    "title": "Bali Tropical Beach Twilight",
    "price": 73,
    "commission": 0.58,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Kuta_Beach_%286924448550%29.jpg/960px-Kuta_Beach_%286924448550%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Kuta%2C_Bali"
  },
  {
    "title": "Stonehenge Ancient Stone Circle",
    "price": 85,
    "commission": 0.68,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Stonehenge2007_07_30.jpg/960px-Stonehenge2007_07_30.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Stonehenge"
  },
  {
    "title": "Vermont Autumn Woodland Wander",
    "price": 89,
    "commission": 0.71,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Momiji_%E7%B4%85%E8%91%89%E3%81%99%E3%82%8B%E3%83%A4%E3%83%9E%E3%83%A2%E3%83%9F%E3%82%B8_B221212.JPG/960px-Momiji_%E7%B4%85%E8%91%89%E3%81%99%E3%82%8B%E3%83%A4%E3%83%9E%E3%83%A2%E3%83%9F%E3%82%B8_B221212.JPG",
    "imageSource": "https://en.wikipedia.org/wiki/Autumn_leaf_color"
  },
  {
    "title": "Vancouver City Lights Over the Bay",
    "price": 73,
    "commission": 0.58,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Skyline_of_Vancouver%2C_Canada.jpg/960px-Skyline_of_Vancouver%2C_Canada.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Vancouver"
  },
  {
    "title": "Zambezi River Emerald Rapids Quest",
    "price": 52,
    "commission": 0.42,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/b/be/Zambezi_River_at_junction_of_Namibia%2C_Zambia%2C_Zimbabwe_%26_Botswana.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Zambezi"
  },
  {
    "title": "California Coast Pacific Highway Reverie",
    "price": 71,
    "commission": 0.57,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Bixby_Creek_Bridge%2C_California%2C_USA_-_May_2013.jpg/960px-Bixby_Creek_Bridge%2C_California%2C_USA_-_May_2013.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Bixby_Bridge"
  },
  {
    "title": "Hallstatt Mirror Lake Reflections",
    "price": 51,
    "commission": 0.41,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Hallstatt_-_Zentrum_.JPG/960px-Hallstatt_-_Zentrum_.JPG",
    "imageSource": "https://en.wikipedia.org/wiki/Hallstatt"
  },
  {
    "title": "Dubai Marina Skyline Shimmer",
    "price": 73,
    "commission": 0.58,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Dubai_Marina_Skyline.jpg/960px-Dubai_Marina_Skyline.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Dubai_Marina"
  },
  {
    "title": "Shanghai Neon River Radiance",
    "price": 93,
    "commission": 0.74,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Bund_2.jpg/960px-The_Bund_2.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/The_Bund"
  },
  {
    "title": "London Thames Twilight Majesty",
    "price": 79,
    "commission": 0.63,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/London_Thames_Sunset_panorama_-_Feb_2008.jpg/960px-London_Thames_Sunset_panorama_-_Feb_2008.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/River_Thames"
  },
  {
    "title": "New York Foggy Manhattan Emergence",
    "price": 87,
    "commission": 0.7,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Lower_Manhattan_from_Jersey_City_September_2020_HDR_panorama_%28cropped%29.jpg/960px-Lower_Manhattan_from_Jersey_City_September_2020_HDR_panorama_%28cropped%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/World_Trade_Center_(2001%E2%80%93present)"
  },
  {
    "title": "Chicago Lakeshore Skyline Panorama",
    "price": 51,
    "commission": 0.41,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Chicago_River_ferry_b.jpg/960px-Chicago_River_ferry_b.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Chicago"
  },
  {
    "title": "Hong Kong Night Market Rush",
    "price": 70,
    "commission": 0.56,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/GateOfTempleInHongKong.jpg/960px-GateOfTempleInHongKong.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Temple_Street%2C_Hong_Kong"
  },
  {
    "title": "Valencia Opera House Lightshow",
    "price": 82,
    "commission": 0.66,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/El_Palau_de_les_Arts_Reina_Sof%C3%ADa%2C_Valencia_-_Jan_2007.jpg/960px-El_Palau_de_les_Arts_Reina_Sof%C3%ADa%2C_Valencia_-_Jan_2007.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Palau_de_les_Arts_Reina_Sof%C3%ADa"
  },
  {
    "title": "Tokyo Shinjuku Futuristic Nexus",
    "price": 61,
    "commission": 0.49,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Skyscrapers_of_Shinjuku_2009_January.jpg/960px-Skyscrapers_of_Shinjuku_2009_January.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Shinjuku"
  },
  {
    "title": "London Trafalgar Square Panorama",
    "price": 71,
    "commission": 0.57,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Trafalgar_Square%2C_London_2_-_Jun_2009.jpg/960px-Trafalgar_Square%2C_London_2_-_Jun_2009.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Trafalgar_Square"
  },
  {
    "title": "New York Empire State Beacon",
    "price": 93,
    "commission": 0.74,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/1/10/Empire_State_Building_%28aerial_view%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Empire_State_Building"
  },
  {
    "title": "Manhattan Financial District Golden Horizon",
    "price": 74,
    "commission": 0.59,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/NYC_Downtown_Manhattan_Skyline_seen_from_Paulus_Hook_2019-12-20_IMG_7347_FRD.jpg/960px-NYC_Downtown_Manhattan_Skyline_seen_from_Paulus_Hook_2019-12-20_IMG_7347_FRD.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Financial_District%2C_Manhattan"
  },
  {
    "title": "Big Sur Coastal Highway Drive",
    "price": 98,
    "commission": 0.78,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Central_Californian_Coastline%2C_Big_Sur_-_May_2013.jpg/960px-Central_Californian_Coastline%2C_Big_Sur_-_May_2013.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Big_Sur"
  },
  {
    "title": "Manhattan West Side Sunset Skyline",
    "price": 76,
    "commission": 0.61,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Midtown_Manhattan_from_Weehawken_September_2021_HDR.jpg/960px-Midtown_Manhattan_from_Weehawken_September_2021_HDR.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Hudson_Yards_(development)"
  },
  {
    "title": "Monument Valley Desert Vista",
    "price": 91,
    "commission": 0.73,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Monument_Valley%2C_Utah%2C_USA_%2823611451292%29.jpg/960px-Monument_Valley%2C_Utah%2C_USA_%2823611451292%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Monument_Valley"
  },
  {
    "title": "Los Angeles Hollywood Hills Landmark",
    "price": 77,
    "commission": 0.62,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Hollywood_sign_%288485145044%29.jpg/960px-Hollywood_sign_%288485145044%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Hollywood_Sign"
  },
  {
    "title": "Zion National Park Canyon Panorama",
    "price": 65,
    "commission": 0.52,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zion_angels_landing_view.jpg/960px-Zion_angels_landing_view.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Zion_National_Park"
  },
  {
    "title": "New York Times Square Glow",
    "price": 64,
    "commission": 0.51,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/New_york_times_square-terabass.jpg/960px-New_york_times_square-terabass.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Times_Square"
  },
  {
    "title": "Brooklyn Bridge Luminescence",
    "price": 96,
    "commission": 0.77,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Brooklyn_Bridge_and_the_Lower_Manhattan_skyline_from_Pebble_Beach%2C_New_York.jpg/960px-Brooklyn_Bridge_and_the_Lower_Manhattan_skyline_from_Pebble_Beach%2C_New_York.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Brooklyn_Bridge"
  },
  {
    "title": "Lower Manhattan Downtown City Lights",
    "price": 93,
    "commission": 0.74,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Luchtfoto_van_Lower_Manhattan.jpg/960px-Luchtfoto_van_Lower_Manhattan.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Lower_Manhattan"
  },
  {
    "title": "Midtown Manhattan Urban Tapestry",
    "price": 52,
    "commission": 0.42,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/West_side_of_Manhattan_from_Hudson_Commons_%2895103p%29.jpg/960px-West_side_of_Manhattan_from_Hudson_Commons_%2895103p%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Midtown_Manhattan"
  },
  {
    "title": "Gotham (NYC) Cityscape Overview",
    "price": 86,
    "commission": 0.69,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg/960px-View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/List_of_tallest_buildings_in_New_York_City"
  },
  {
    "title": "New York Harbor Lady Liberty’s Embrace",
    "price": 56,
    "commission": 0.45,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Front_view_of_Statue_of_Liberty_%28cropped%29.jpg/960px-Front_view_of_Statue_of_Liberty_%28cropped%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Statue_of_Liberty"
  },
  {
    "title": "Broadway, NYC Neon Spectacle",
    "price": 70,
    "commission": 0.56,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Broadway_looking_north_from_48th_Street_Manhattan.jpeg/960px-Broadway_looking_north_from_48th_Street_Manhattan.jpeg",
    "imageSource": "https://en.wikipedia.org/wiki/Broadway_(Manhattan)"
  },
  {
    "title": "Bora Bora Tropical Atoll Dreams",
    "price": 58,
    "commission": 0.46,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Bora_Bora_ISS006.jpg/960px-Bora_Bora_ISS006.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Bora_Bora"
  },
  {
    "title": "Zermatt Alpine Snow Summit",
    "price": 88,
    "commission": 0.7,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/1_zermatt_evening_2022.jpg/960px-1_zermatt_evening_2022.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Zermatt"
  },
  {
    "title": "Hawaii’s North Shore Oceanic Foam Currents",
    "price": 67,
    "commission": 0.54,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/North_Shore_Hawaii_filmed_with_a_drone.webm/960px--North_Shore_Hawaii_filmed_with_a_drone.webm.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/North_Shore_(O%CA%BBahu)"
  },
  {
    "title": "Oregon Misty Pine Grove",
    "price": 53,
    "commission": 0.42,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/OregonCoastEcola_Edit.jpg/960px-OregonCoastEcola_Edit.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Oregon_Coast"
  },
  {
    "title": "UK Jurassic Coast Cliffside Majesty",
    "price": 74,
    "commission": 0.59,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Gad_cliff_dorset.jpg/960px-Gad_cliff_dorset.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Jurassic_Coast"
  },
  {
    "title": "Amalfi Coast Mediterranean Drive",
    "price": 63,
    "commission": 0.5,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Amalfi_Coast_%28Italy%2C_October_2020%29_-_75_%2850558355441%29.jpg/960px-Amalfi_Coast_%28Italy%2C_October_2020%29_-_75_%2850558355441%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Amalfi_Coast"
  },
  {
    "title": "Lake Como Emerald Alpine Reflections",
    "price": 99,
    "commission": 0.79,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Sentiero_del_Viandante_DSC_6340_%2814020554463%29.jpg/960px-Sentiero_del_Viandante_DSC_6340_%2814020554463%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Lake_Como"
  },
  {
    "title": "Portland Japanese Garden Greenwood Bridge Passage",
    "price": 58,
    "commission": 0.46,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Japanese_Garden_-1.jpg/960px-Japanese_Garden_-1.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Portland_Japanese_Garden"
  },
  {
    "title": "Scottish Highlands Autumn Highland Splendor",
    "price": 75,
    "commission": 0.6,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/0/03/Buachaille_Etive_Mor.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Buachaille_Etive_M%C3%B2r"
  },
  {
    "title": "Paris Eiffel Tower Golden Hour",
    "price": 84,
    "commission": 0.67,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg/960px-Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Eiffel_Tower"
  },
  {
    "title": "Rome Colosseum Ancient Grandeur",
    "price": 76,
    "commission": 0.61,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Colosseo_2020.jpg/960px-Colosseo_2020.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Colosseum"
  },
  {
    "title": "Santorini Oia Sunset Reverie",
    "price": 89,
    "commission": 0.71,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Oia_sunset_-_panoramio_%282%29.jpg/960px-Oia_sunset_-_panoramio_%282%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Oia%2C_Greece"
  },
  {
    "title": "Machu Picchu Andean Citadel Dawn",
    "price": 95,
    "commission": 0.76,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Machu_Picchu%2C_2023_%28012%29.jpg/960px-Machu_Picchu%2C_2023_%28012%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Machu_Picchu"
  },
  {
    "title": "Petra Rose City Canyon Passage",
    "price": 82,
    "commission": 0.66,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Al_Deir_Petra.JPG/960px-Al_Deir_Petra.JPG",
    "imageSource": "https://en.wikipedia.org/wiki/Petra"
  },
  {
    "title": "Great Wall of China Mountain Odyssey",
    "price": 91,
    "commission": 0.73,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/The_Great_Wall_of_China_at_Jinshanling-edit.jpg/960px-The_Great_Wall_of_China_at_Jinshanling-edit.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Great_Wall_of_China"
  },
  {
    "title": "Taj Mahal Marble Sunrise Reflection",
    "price": 87,
    "commission": 0.7,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Taj_Mahal_%28Edited%29.jpeg/960px-Taj_Mahal_%28Edited%29.jpeg",
    "imageSource": "https://en.wikipedia.org/wiki/Taj_Mahal"
  },
  {
    "title": "Serengeti Golden Savanna Safari",
    "price": 97,
    "commission": 0.78,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Serengeti-Landscape-2012.JPG/960px-Serengeti-Landscape-2012.JPG",
    "imageSource": "https://en.wikipedia.org/wiki/Serengeti_National_Park"
  },
  {
    "title": "Mount Fuji Lakeside Serenity",
    "price": 73,
    "commission": 0.58,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/View_of_Mount_Fuji_from_%C5%8Cwakudani_20211202.jpg/960px-View_of_Mount_Fuji_from_%C5%8Cwakudani_20211202.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Mount_Fuji"
  },
  {
    "title": "Kyoto Fushimi Inari Torii Trail",
    "price": 69,
    "commission": 0.55,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine%2C_Kyoto%2C_Japan.jpg/960px-Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine%2C_Kyoto%2C_Japan.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Fushimi_Inari-taisha"
  },
  {
    "title": "Sydney Opera House Harbour Glow",
    "price": 86,
    "commission": 0.69,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Sydney_Australia._%2821339175489%29.jpg/960px-Sydney_Australia._%2821339175489%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Sydney_Opera_House"
  },
  {
    "title": "Great Barrier Reef Coral Voyage",
    "price": 94,
    "commission": 0.75,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/ISS-45_StoryOfWater%2C_Great_Barrier_Reef%2C_Australia.jpg/960px-ISS-45_StoryOfWater%2C_Great_Barrier_Reef%2C_Australia.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Great_Barrier_Reef"
  },
  {
    "title": "Queenstown Alpine Adventure",
    "price": 81,
    "commission": 0.65,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Queenstown_1_%288168013172%29.jpg/960px-Queenstown_1_%288168013172%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Queenstown%2C_New_Zealand"
  },
  {
    "title": "Milford Sound Fjord Majesty",
    "price": 88,
    "commission": 0.7,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Milford_Sound_%28New_Zealand%29.JPG/960px-Milford_Sound_%28New_Zealand%29.JPG",
    "imageSource": "https://en.wikipedia.org/wiki/Milford_Sound"
  },
  {
    "title": "Patagonia Torres del Paine Wilderness",
    "price": 96,
    "commission": 0.77,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Torres_del_Paine_y_cuernos_del_Paine%2C_montaje.jpg/960px-Torres_del_Paine_y_cuernos_del_Paine%2C_montaje.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Torres_del_Paine_National_Park"
  },
  {
    "title": "Rio Christ the Redeemer Panorama",
    "price": 79,
    "commission": 0.63,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Christ_the_Redeemer_-_Cristo_Redentor.jpg/960px-Christ_the_Redeemer_-_Cristo_Redentor.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Christ_the_Redeemer_(statue)"
  },
  {
    "title": "Iguazu Falls Rainforest Thunder",
    "price": 83,
    "commission": 0.66,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Aerial_Foz_de_Igua%C3%A7u_26_Nov_2005.jpg/960px-Aerial_Foz_de_Igua%C3%A7u_26_Nov_2005.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Iguazu_Falls"
  },
  {
    "title": "Salar de Uyuni Mirror Horizon",
    "price": 72,
    "commission": 0.58,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Salar_Uyuni_au01.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Salar_de_Uyuni"
  },
  {
    "title": "Galapagos Islands Wildlife Expedition",
    "price": 99,
    "commission": 0.79,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Lobo_marino_%28Zalophus_californianus_wollebaeki%29%2C_Punta_Pitt%2C_isla_de_San_Crist%C3%B3bal%2C_islas_Gal%C3%A1pagos%2C_Ecuador%2C_2015-07-24%2C_DD_11.JPG/960px-Lobo_marino_%28Zalophus_californianus_wollebaeki%29%2C_Punta_Pitt%2C_isla_de_San_Crist%C3%B3bal%2C_islas_Gal%C3%A1pagos%2C_Ecuador%2C_2015-07-24%2C_DD_11.JPG",
    "imageSource": "https://en.wikipedia.org/wiki/Gal%C3%A1pagos_Islands"
  },
  {
    "title": "Chichen Itza Maya Temple Discovery",
    "price": 75,
    "commission": 0.6,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Chichen_Itza_3.jpg/960px-Chichen_Itza_3.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Chichen_Itza"
  },
  {
    "title": "Lake Louise Turquoise Mountain Retreat",
    "price": 85,
    "commission": 0.68,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Lake_Louise_17092005.jpg/960px-Lake_Louise_17092005.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Lake_Louise_(Alberta)"
  },
  {
    "title": "Grand Canyon Sunset Overlook",
    "price": 92,
    "commission": 0.74,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Canyon_River_Tree_%28165872763%29.jpeg/960px-Canyon_River_Tree_%28165872763%29.jpeg",
    "imageSource": "https://en.wikipedia.org/wiki/Grand_Canyon"
  },
  {
    "title": "Yosemite Half Dome Valley Vista",
    "price": 90,
    "commission": 0.72,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Half_Dome_with_Eastern_Yosemite_Valley_%2850MP%29.jpg/960px-Half_Dome_with_Eastern_Yosemite_Valley_%2850MP%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Yosemite_National_Park"
  },
  {
    "title": "Yellowstone Canyon Wilderness",
    "price": 78,
    "commission": 0.62,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/7/73/Grand_Canyon_of_yellowstone.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Yellowstone_National_Park"
  },
  {
    "title": "Niagara Falls Mist and Rainbow",
    "price": 71,
    "commission": 0.57,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/3Falls_Niagara.jpg/960px-3Falls_Niagara.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Niagara_Falls"
  },
  {
    "title": "Canadian Rockies Glacier Passage",
    "price": 93,
    "commission": 0.74,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Snow_Dome%2C_Forbes%2C_Lyells%2C_Et_al_from_Mt._Kitchener.jpg/960px-Snow_Dome%2C_Forbes%2C_Lyells%2C_Et_al_from_Mt._Kitchener.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Canadian_Rockies"
  },
  {
    "title": "Prague Charles Bridge Dawn Walk",
    "price": 68,
    "commission": 0.54,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Prague_07-2016_view_from_Lesser_Town_Tower_of_Charles_Bridge_img3.jpg/960px-Prague_07-2016_view_from_Lesser_Town_Tower_of_Charles_Bridge_img3.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Charles_Bridge"
  },
  {
    "title": "Budapest Parliament Danube Lights",
    "price": 77,
    "commission": 0.62,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Hungarian_Parliament_Building_from_across_the_Danube%2C_2025-01-11.jpg/960px-Hungarian_Parliament_Building_from_across_the_Danube%2C_2025-01-11.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Hungarian_Parliament_Building"
  },
  {
    "title": "Vienna Schonbrunn Imperial Gardens",
    "price": 74,
    "commission": 0.59,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Wien_-_Schloss_Sch%C3%B6nbrunn.JPG/960px-Wien_-_Schloss_Sch%C3%B6nbrunn.JPG",
    "imageSource": "https://en.wikipedia.org/wiki/Sch%C3%B6nbrunn_Palace"
  },
  {
    "title": "Barcelona Sagrada Familia Spires",
    "price": 80,
    "commission": 0.64,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/SF_maig_2_cropped.jpg/960px-SF_maig_2_cropped.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Sagrada_Fam%C3%ADlia"
  },
  {
    "title": "Lisbon Belem Tower Riverside",
    "price": 66,
    "commission": 0.53,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Bel%C3%A9m_Tower_in_Lisbon%2C_Portugal.jpg/960px-Bel%C3%A9m_Tower_in_Lisbon%2C_Portugal.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Bel%C3%A9m_Tower"
  },
  {
    "title": "Porto Douro Valley River Journey",
    "price": 70,
    "commission": 0.56,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Rio_Douro_-_Portugal_%2832615481975%29_%28cropped%29.jpg/960px-Rio_Douro_-_Portugal_%2832615481975%29_%28cropped%29.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Douro"
  },
  {
    "title": "Amsterdam Herengracht Canal Charm",
    "price": 73,
    "commission": 0.58,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Gerrit_Adriaensz._Berckheyde_-_De_bocht_van_de_Herengracht_te_Amsterdam.jpg/960px-Gerrit_Adriaensz._Berckheyde_-_De_bocht_van_de_Herengracht_te_Amsterdam.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Herengracht"
  },
  {
    "title": "Brussels Grand Place Evening Glow",
    "price": 67,
    "commission": 0.54,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Grand-Place%2C_Brussels_-_panorama%2C_June_2018.jpg/960px-Grand-Place%2C_Brussels_-_panorama%2C_June_2018.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Grand-Place"
  },
  {
    "title": "Copenhagen Nyhavn Harbour Colors",
    "price": 76,
    "commission": 0.61,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/The_Nyhavn_Canal_3.jpg/960px-The_Nyhavn_Canal_3.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Nyhavn"
  },
  {
    "title": "Stockholm Gamla Stan Old Town",
    "price": 72,
    "commission": 0.58,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Gamla_stan_September_2014_01.jpg/960px-Gamla_stan_September_2014_01.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Gamla_Stan"
  },
  {
    "title": "Norway Geirangerfjord Scenic Voyage",
    "price": 98,
    "commission": 0.78,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Geirangerfjord_.jpg/960px-Geirangerfjord_.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Geirangerfjord"
  },
  {
    "title": "Lofoten Arctic Fishing Villages",
    "price": 91,
    "commission": 0.73,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Moskenes_Reinebringen_lub_2025-07-21_img09_Aussicht.jpg/960px-Moskenes_Reinebringen_lub_2025-07-21_img09_Aussicht.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Lofoten"
  },
  {
    "title": "Lapland Aurora Borealis Night",
    "price": 89,
    "commission": 0.71,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Aurora_borealis_over_Eielson_Air_Force_Base%2C_Alaska.jpg/960px-Aurora_borealis_over_Eielson_Air_Force_Base%2C_Alaska.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Aurora"
  },
  {
    "title": "Marrakech Jemaa el-Fnaa Evening",
    "price": 64,
    "commission": 0.51,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Djemaa_el_Fna.jpg/960px-Djemaa_el_Fna.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Jemaa_el-Fnaa"
  },
  {
    "title": "Cairo Giza Pyramids Desert Legacy",
    "price": 86,
    "commission": 0.69,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Pyramids_of_the_Giza_Necropolis.jpg/960px-Pyramids_of_the_Giza_Necropolis.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Giza_pyramid_complex"
  },
  {
    "title": "Wadi Rum Red Desert Expedition",
    "price": 82,
    "commission": 0.66,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Mountain_in_Wadi_Rum%2C_Jordan.jpg/960px-Mountain_in_Wadi_Rum%2C_Jordan.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Wadi_Rum"
  },
  {
    "title": "Dead Sea Salt Shore Retreat",
    "price": 65,
    "commission": 0.52,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Dead_Sea_beach_00.JPG/960px-Dead_Sea_beach_00.JPG",
    "imageSource": "https://en.wikipedia.org/wiki/Dead_Sea"
  },
  {
    "title": "Singapore Marina Bay Skyline",
    "price": 88,
    "commission": 0.7,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Marina_Bay_Singapore-3499.jpg/960px-Marina_Bay_Singapore-3499.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Marina_Bay%2C_Singapore"
  },
  {
    "title": "Kuala Lumpur Petronas Skyline",
    "price": 75,
    "commission": 0.6,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Sky_Deck_at_Kuala_Lumpur_Tower_%28Menara_KL%29%2C_Malaysia_on_28_July_2020_at_172828.jpg/960px-Sky_Deck_at_Kuala_Lumpur_Tower_%28Menara_KL%29%2C_Malaysia_on_28_July_2020_at_172828.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Kuala_Lumpur_City_Centre"
  },
  {
    "title": "Bangkok Grand Palace Golden Splendor",
    "price": 69,
    "commission": 0.55,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/0005574_-_Wat_Phra_Kaew_006.jpg/960px-0005574_-_Wat_Phra_Kaew_006.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Grand_Palace"
  },
  {
    "title": "Ha Long Bay Limestone Voyage",
    "price": 84,
    "commission": 0.67,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Ha_Long_Bay_in_2019.jpg/960px-Ha_Long_Bay_in_2019.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/H%E1%BA%A1_Long_Bay"
  },
  {
    "title": "Angkor Wat Jungle Temple Sunrise",
    "price": 90,
    "commission": 0.72,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Angkor_Wat.jpg/960px-Angkor_Wat.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Angkor_Wat"
  },
  {
    "title": "Seoul Gyeongbokgung Palace Walk",
    "price": 71,
    "commission": 0.57,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/%EA%B4%91%ED%99%94%EB%AC%B8_%EC%9B%94%EB%8C%80.jpg/960px-%EA%B4%91%ED%99%94%EB%AC%B8_%EC%9B%94%EB%8C%80.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Gyeongbokgung"
  },
  {
    "title": "Zhangjiajie Avatar Mountain Peaks",
    "price": 95,
    "commission": 0.76,
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/1_tianzishan_wulingyuan_zhangjiajie_2012.jpg/960px-1_tianzishan_wulingyuan_zhangjiajie_2012.jpg",
    "imageSource": "https://en.wikipedia.org/wiki/Zhangjiajie_National_Forest_Park"
  }
];
