const existingWikiPages = [
  "Golden Gate Bridge",
  "Tourism in the Maldives",
  "Cappadocia",
  "Shibuya Crossing",
  "Banff National Park",
  "La Digue",
  "Bernese Alps",
  "Black Forest",
  "Plitvice Lakes National Park",
  "Venice",
  "Sk\u00f3gafoss",
  "Kuta Beach",
  "Stonehenge",
  "Autumn leaf color",
  "Vancouver",
  "Zambezi",
  "Bixby Creek Bridge",
  "Hallstatt",
  "Dubai Marina",
  "The Bund",
  "River Thames",
  "World Trade Center (2001\u2013present)",
  "Chicago",
  "Temple Street, Hong Kong",
  "Palau de les Arts Reina Sof\u00eda",
  "Shinjuku",
  "Trafalgar Square",
  "Empire State Building",
  "Financial District, Manhattan",
  "Big Sur",
  "Hudson Yards (development)",
  "Monument Valley",
  "Hollywood Sign",
  "Zion National Park",
  "Times Square",
  "Brooklyn Bridge",
  "Lower Manhattan",
  "Midtown Manhattan",
  "Skyline of New York City",
  "Statue of Liberty",
  "Broadway (Manhattan)",
  "Bora Bora",
  "Zermatt",
  "North Shore (Oahu)",
  "Oregon Coast",
  "Jurassic Coast",
  "Amalfi Coast",
  "Lake Como",
  "Portland Japanese Garden",
  "Buachaille Etive M\u00f2r",
];

const newTreks = [
  ["Paris Eiffel Tower Golden Hour", 84, "Eiffel Tower"],
  ["Rome Colosseum Ancient Grandeur", 76, "Colosseum"],
  ["Santorini Oia Sunset Reverie", 89, "Oia, Greece"],
  ["Machu Picchu Andean Citadel Dawn", 95, "Machu Picchu"],
  ["Petra Rose City Canyon Passage", 82, "Petra"],
  ["Great Wall of China Mountain Odyssey", 91, "Great Wall of China"],
  ["Taj Mahal Marble Sunrise Reflection", 87, "Taj Mahal"],
  ["Serengeti Golden Savanna Safari", 97, "Serengeti National Park"],
  ["Mount Fuji Lakeside Serenity", 73, "Mount Fuji"],
  ["Kyoto Fushimi Inari Torii Trail", 69, "Fushimi Inari-taisha"],
  ["Sydney Opera House Harbour Glow", 86, "Sydney Opera House"],
  ["Great Barrier Reef Coral Voyage", 94, "Great Barrier Reef"],
  ["Queenstown Alpine Adventure", 81, "Queenstown, New Zealand"],
  ["Milford Sound Fjord Majesty", 88, "Milford Sound"],
  ["Patagonia Torres del Paine Wilderness", 96, "Torres del Paine National Park"],
  ["Rio Christ the Redeemer Panorama", 79, "Christ the Redeemer (statue)"],
  ["Iguazu Falls Rainforest Thunder", 83, "Iguazu Falls"],
  ["Salar de Uyuni Mirror Horizon", 72, "Salar de Uyuni"],
  ["Galapagos Islands Wildlife Expedition", 99, "Gal\u00e1pagos Islands"],
  ["Chichen Itza Maya Temple Discovery", 75, "Chichen Itza"],
  ["Lake Louise Turquoise Mountain Retreat", 85, "Lake Louise (Alberta)"],
  ["Grand Canyon Sunset Overlook", 92, "Grand Canyon"],
  ["Yosemite Half Dome Valley Vista", 90, "Yosemite National Park"],
  ["Yellowstone Canyon Wilderness", 78, "Yellowstone National Park"],
  ["Niagara Falls Mist and Rainbow", 71, "Niagara Falls"],
  ["Canadian Rockies Glacier Passage", 93, "Canadian Rockies"],
  ["Prague Charles Bridge Dawn Walk", 68, "Charles Bridge"],
  ["Budapest Parliament Danube Lights", 77, "Hungarian Parliament Building"],
  ["Vienna Schonbrunn Imperial Gardens", 74, "Sch\u00f6nbrunn Palace"],
  ["Barcelona Sagrada Familia Spires", 80, "Sagrada Fam\u00edlia"],
  ["Lisbon Belem Tower Riverside", 66, "Bel\u00e9m Tower"],
  ["Porto Douro Valley River Journey", 70, "Douro"],
  ["Amsterdam Herengracht Canal Charm", 73, "Herengracht"],
  ["Brussels Grand Place Evening Glow", 67, "Grand-Place"],
  ["Copenhagen Nyhavn Harbour Colors", 76, "Nyhavn"],
  ["Stockholm Gamla Stan Old Town", 72, "Gamla Stan"],
  ["Norway Geirangerfjord Scenic Voyage", 98, "Geirangerfjord"],
  ["Lofoten Arctic Fishing Villages", 91, "Lofoten"],
  ["Lapland Aurora Borealis Night", 89, "Aurora borealis"],
  ["Marrakech Jemaa el-Fnaa Evening", 64, "Jemaa el-Fnaa"],
  ["Cairo Giza Pyramids Desert Legacy", 86, "Giza pyramid complex"],
  ["Wadi Rum Red Desert Expedition", 82, "Wadi Rum"],
  ["Dead Sea Salt Shore Retreat", 65, "Dead Sea"],
  ["Singapore Marina Bay Skyline", 88, "Marina Bay, Singapore"],
  ["Kuala Lumpur Petronas Skyline", 75, "Kuala Lumpur City Centre"],
  ["Bangkok Grand Palace Golden Splendor", 69, "Grand Palace"],
  ["Ha Long Bay Limestone Voyage", 84, "H\u1ea1 Long Bay"],
  ["Angkor Wat Jungle Temple Sunrise", 90, "Angkor Wat"],
  ["Seoul Gyeongbokgung Palace Walk", 71, "Gyeongbokgung"],
  ["Zhangjiajie Avatar Mountain Peaks", 95, "Zhangjiajie National Forest Park"],
];

module.exports = { existingWikiPages, newTreks };
