const jwt = require("jsonwebtoken");
const bcrypt = require("bcrypt");
const User = require("../../models/User");
const Response = require("../../utils/response");
const { publicUser } = require("../../utils/mongoResponse");
const jwtSecret = process.env.JWT_SECRET || process.env.ACCESS_TOKEN_SECRET;
const jwtExpiresIn = process.env.JWT_EXPIRES_IN || "1h";

const register = async (req,res)=>{ try { const {userName,email,password,referralCode,withdrawCode}=req.body; const role=req.body.role||"user"; if(!["user","manager"].includes(role)) return res.status(403).json(new Response(null,"This role can only be created by an administrator",403,"error")); if(!userName||!email||!password) return res.status(400).json(new Response(null,"Username, email and password are required",400,"error")); if(await User.exists({$or:[{userName},{email:email.toLowerCase()}]})) return res.status(409).json(new Response(null,"Username or email already exists",409,"error")); let referredBy=null; if(role==="manager"||role==="user"){ if(!referralCode) return res.status(400).json(new Response(null,`Referral code is required for ${role}`,400,"error")); const expectedRole=role==="manager"?"admin":"manager"; const referrer=await User.findOne({referralCode,role:expectedRole}); if(!referrer) return res.status(400).json(new Response(null,`Invalid ${expectedRole} referral code`,400,"error")); referredBy=referrer._id; } const user=await User.create({userName,email,password:await bcrypt.hash(String(password),10),role,referralCode:null,withdrawCode,referredBy,record:role==="user"?{totalBalance:15}:undefined}); return res.status(201).json(new Response({userName:user.userName,email:user.email},"Registered successfully",201)); } catch(error){ console.error("Registration error:",error.message); return res.status(500).json(new Response(null,"Internal Server Error",500,"error")); } };
const login=async(req,res)=>{ try { const {email,password}=req.body; const user=await User.findOne({email:String(email||"").toLowerCase()}).select("+password"); if(!user||!user.active||!password||!(await bcrypt.compare(String(password),user.password))) return res.status(401).json(new Response(null,"Invalid Email or Password",401,"error")); const token=jwt.sign({id:user._id.toString(),userName:user.userName,email:user.email,role:user.role},jwtSecret,{expiresIn:jwtExpiresIn}); return res.json(new Response({token,user:publicUser(user,user.role==="user")},"Login successful",200)); } catch(error){ console.error("Login error:",error.message); return res.status(500).json(new Response(null,"Internal Server Error at userLogin",500,"error")); } };
const verifyToken=async(req,res,next)=>{ const header=req.headers.authorization||req.headers.Authorization; if(!header?.startsWith("Bearer ")) return res.status(403).json(new Response(null,"No token provided",403)); try { const decoded=jwt.verify(header.split(" ")[1],jwtSecret); const user=await User.findById(decoded.id); if(!user) return res.status(404).json(new Response(null,"User not found",404)); req.user=publicUser(user,user.role==="user"); next(); } catch(error){ if(["JsonWebTokenError","TokenExpiredError","CastError"].includes(error.name)) return res.status(401).json(new Response(null,"Invalid or expired token",401)); console.error("Token verification error:",error.message); return res.status(500).json(new Response(null,"Internal server error",500)); } };
const verifyUser=(req,res,next)=>{ const token=req.cookies.token; if(!token) return res.status(401).json({Error:"you are not authorized"}); try{req.name=jwt.verify(token,jwtSecret).name; next();}catch{return res.status(401).json({message:"Unauthorized or invalid token"});} };
const displayUsers=async(req,res)=>{ try{const users=await User.find({},"userName").lean(); return res.json(new Response(users.map(u=>({id:u._id.toString(),userName:u.userName})),users.length?"Data fetched successfully":"No data Found",users.length?201:200));}catch(error){console.error("Error fetching users:",error.message);return res.status(500).json({message:"Internal server error",status:"error"});} };
const logout=(req,res)=>{res.clearCookie("token");return res.json({Status:201});};
const refreshToken=async(req,res)=>{const header=req.headers.authorization||req.headers.Authorization;if(!header?.startsWith("Bearer "))return res.status(401).json(new Response(null,"No token provided",401));try{const decoded=jwt.verify(header.split(" ")[1],jwtSecret);const user=await User.findById(decoded.id);if(!user)return res.status(404).json(new Response(null,"User not found",404));const token=jwt.sign({id:user._id.toString(),userName:user.userName,email:user.email,role:user.role},jwtSecret,{expiresIn:jwtExpiresIn});return res.json(new Response({token},"Token refreshed successfully",200));}catch(error){return res.status(401).json(new Response(null,"Invalid or expired token",401));}};
module.exports={register,login,verifyToken,verifyUser,logout,displayUsers,refreshToken};