import React, { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { ArrowRight, ArrowUpRight, Bell, CalendarDays, Check, CheckCircle2, ChevronDown, ChevronRight, Compass, CreditCard, Download, Globe2, Heart, HelpCircle, LayoutDashboard, Map, MapPin, Menu, MessageCircle, Plus, Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles, Users, X } from "lucide-react";
import "./preview.css";

// Isolated design review: sample records only. No API, storage, auth or payment connections.
const PHOTO = (id, width = 1200) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;
const TRIPS = [
  { id: 1, name: "An Italian state of mind", place: "Italy", region: "Europe", days: 10, image: "photo-1516483638261-f4dbaf036963", label: "Coast & culture", route: "Rome · Florence · Cinque Terre", date: "12–21 October 2026", status: "Confirmed", description: "Wander through Florence, slow down over a long lunch, and follow the coast to the colorful villages of Cinque Terre." },
  { id: 2, name: "Japan, beyond the ordinary", place: "Japan", region: "Asia", days: 12, image: "photo-1493976040374-85c8e12f0c0e", label: "Tradition & discovery", route: "Tokyo · Hakone · Kyoto", date: "8–19 April 2027", status: "Planning", description: "From Tokyo's lively neighborhoods to quiet gardens in Kyoto, make room for the details that give Japan its character." },
  { id: 3, name: "A little Swiss wonder", place: "Switzerland", region: "Europe", days: 8, image: "photo-1476514525535-07fb3b4ae5f1", label: "Mountains & moments", route: "Zurich · Lucerne · Interlaken", date: "5–12 June 2027", status: "Available", description: "Lakeside walks, mountain views, and unhurried afternoons. Discover a different side of Switzerland at every stop." },
  { id: 4, name: "The magic of the Greek islands", place: "Greece", region: "Europe", days: 9, image: "photo-1570077188670-e3a8d69ac5ff", label: "Island life", route: "Athens · Mykonos · Santorini", date: "2–10 May 2027", status: "Available", description: "Ancient streets meet blue horizons on a journey through Athens and the sunlit islands of the Aegean." },
  { id: 5, name: "Morocco in full color", place: "Morocco", region: "Africa", days: 11, image: "photo-1519451241324-20b4ea2c4220", label: "Food & local life", route: "Marrakech · Fes · Casablanca", date: "15–25 March 2027", status: "Available", description: "Explore markets, intricate architecture, and the flavors of Morocco, with space to pause and take it all in." },
  { id: 6, name: "The great American outdoors", place: "United States", region: "Americas", days: 8, image: "photo-1472396961693-142e6e269027", label: "Into the wild", route: "Jackson · Grand Teton · Yellowstone", date: "6–13 July 2027", status: "Available", description: "Wide-open landscapes and extraordinary wildlife create the setting for a journey through the American West." },
];
const INITIAL_TRAVELERS = [
  { name: "Alex Morgan", email: "alex@example.com", trip: "Italy", status: "Confirmed", initials: "AM" },
  { name: "Jamie Chen", email: "jamie@example.com", trip: "Japan", status: "Planning", initials: "JC" },
  { name: "Sam Rivera", email: "sam@example.com", trip: "Greece", status: "Confirmed", initials: "SR" },
  { name: "Riley Parker", email: "riley@example.com", trip: "Switzerland", status: "Confirmed", initials: "RP" },
  { name: "Jordan Ellis", email: "jordan@example.com", trip: "Morocco", status: "Planning", initials: "JE" },
  { name: "Casey Blake", email: "casey@example.com", trip: "United States", status: "Confirmed", initials: "CB" },
];
const INITIAL_TEAM = [ { name: "Taylor Brooks", job: "Travel manager", initials: "TB" }, { name: "Avery Quinn", job: "Guest experience", initials: "AQ" }, { name: "Morgan Lee", job: "Travel manager", initials: "ML" } ];
const NAVS = {
  traveler: [["Overview", LayoutDashboard], ["My journeys", Map], ["Saved places", Heart], ["Payments", CreditCard], ["Profile", Settings], ["Help & support", HelpCircle]],
  admin: [["Overview", LayoutDashboard], ["Travelers", Users], ["Journey catalog", Compass], ["Enquiries", MessageCircle], ["Team", Users], ["Settings", Settings]],
  manager: [["Overview", LayoutDashboard], ["Travelers", Users], ["Journey catalog", Compass], ["Enquiries", MessageCircle], ["Team", Users], ["Settings", Settings]],
};

function Logo() { return <img className="brand-logo" src="/trafalgar-logo.png" alt="Trafalgar" width="324" height="88" />; }
function Badge({ children }) { return <span className={`badge ${["Confirmed", "Ready", "Active", "Paid"].includes(children) ? "green" : "amber"}`}><span />{children}</span>; }
function Photo({ trip, className = "", eager = false }) { return <img className={className} src={PHOTO(trip.image)} alt={`${trip.place} destination inspiration`} loading={eager ? "eager" : "lazy"} />; }
function Action({ children, onClick, secondary = false, ...props }) { return <button className={`action ${secondary ? "secondary" : ""}`} onClick={onClick} {...props}>{children}</button>; }
function Heading({ eyebrow, title, text, action }) { return <div className="section-heading"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{text && <p className="muted">{text}</p>}</div>{action}</div>; }

function TripCard({ trip, saved, onSave, onOpen }) {
  return <article className="trip-card"><div className="trip-photo"><Photo trip={trip} /><span className="photo-tag">{trip.label}</span><button className={`save-place ${saved ? "saved" : ""}`} onClick={() => onSave(trip.id)} aria-label={`${saved ? "Unsave" : "Save"} ${trip.place}`} aria-pressed={saved}><Heart size={18} fill={saved ? "currentColor" : "none"} /></button></div><div className="trip-copy"><p className="trip-region">{trip.region} <span>•</span> {trip.days} days</p><h3>{trip.name}</h3><p className="muted route">{trip.route}</p><button className="text-link" onClick={() => onOpen(trip)}>Explore journey <ArrowUpRight size={17} /></button></div></article>;
}

function Dialog({ children, title, close }) {
  const dialog = useRef(null);
  useEffect(() => { const element = dialog.current; element.showModal(); return () => element.close(); }, []);
  return <dialog ref={dialog} className="preview-dialog" onCancel={close} onClick={e => { if (e.target === dialog.current) close(); }} aria-labelledby="dialog-title"><div className="dialog-top"><h2 id="dialog-title">{title}</h2><button className="icon-button" onClick={close} aria-label="Close dialog"><X /></button></div>{children}</dialog>;
}

function PublicHome({ go, saved, toggleSave, openTrip }) {
  const [region, setRegion] = useState("All destinations");
  const [mobile, setMobile] = useState(false);
  const [query, setQuery] = useState("");
  const [submittedQuery, setSubmittedQuery] = useState("");
  const trips = TRIPS.filter(t => (region === "All destinations" || t.region === region) && `${t.name} ${t.place}`.toLowerCase().includes(submittedQuery.toLowerCase()));
  return <div className="public-view"><header className="public-header"><a href="#top" aria-label="Trafalgar preview home"><Logo /></a><nav aria-label="Homepage navigation"><a href="#destinations">Destinations</a><a href="#experiences">The experience</a><a href="#difference">Why guided travel?</a></nav><button className="public-signin" onClick={() => go("traveler")}>My travel <ArrowUpRight size={16} /></button><button className="icon-button mobile-toggle" aria-label="Toggle navigation" aria-expanded={mobile} onClick={() => setMobile(!mobile)}>{mobile ? <X /> : <Menu />}</button></header>{mobile && <nav className="public-mobile" aria-label="Mobile homepage navigation"><a href="#destinations" onClick={() => setMobile(false)}>Destinations</a><a href="#experiences" onClick={() => setMobile(false)}>The experience</a><button onClick={() => go("traveler")}>My travel <ArrowRight size={16} /></button></nav>}
  <main id="top"><section className="home-hero"><div className="hero-copy"><p className="eyebrow"><span className="red-line" /> A world of real connections</p><h1>Go beyond<br />the <span>postcard.</span></h1><p>Find the places that move you. Meet the people who make them. Bring home a story that is entirely your own.</p><a className="action" href="#destinations">Find your next journey <ArrowRight size={18} /></a><div className="hero-footnote"><Globe2 size={19} /><span>Remarkable places. A more personal perspective.</span></div></div><div className="hero-image"><Photo trip={TRIPS[0]} eager /><div className="photo-caption"><MapPin size={16} /> Cinque Terre, Italy</div><div className="hero-note"><span className="note-circle"><Compass size={24} /></span><div><strong>Take the scenic route.</strong><p>There's a story around every corner.</p></div></div></div></section>
  <section className="search-strip" aria-label="Find destinations"><div><span className="eyebrow">Where will curiosity take you?</span><h2>Your next chapter starts here.</h2></div><form onSubmit={e => { e.preventDefault(); setSubmittedQuery(query); document.getElementById("destinations").scrollIntoView({ behavior: "smooth" }); }}><label htmlFor="destination-search" className="sr-only">Search destinations</label><Search size={20} /><input id="destination-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Try Italy, Japan, or Switzerland" /><button type="submit" aria-label="Search destinations"><ArrowRight size={23} /></button></form></section>
  <section className="public-section" id="destinations"><Heading eyebrow="Follow your curiosity" title="A world worth getting to know." text="A little inspiration for the journey you've been thinking about." /><div className="filter-tabs" aria-label="Destination region">{["All destinations", "Europe", "Asia", "Africa", "Americas"].map(r => <button key={r} onClick={() => setRegion(r)} className={region === r ? "active" : ""} aria-pressed={region === r}>{r}</button>)}</div><div className="destination-grid">{trips.map(trip => <TripCard key={trip.id} trip={trip} saved={saved.includes(trip.id)} onSave={toggleSave} onOpen={openTrip} />)}</div>{!trips.length && <div className="empty-state"><Search /><h3>No destinations match that search.</h3><button className="text-link" onClick={() => { setQuery(""); setSubmittedQuery(""); setRegion("All destinations"); }}>Show all destinations <ArrowRight size={16} /></button></div>}</section>
  <section className="experience-section" id="experiences"><div className="experience-image"><img src={PHOTO("photo-1552566626-52f8b828add9")} alt="A welcoming restaurant table ready for guests" loading="lazy" /><span>Good food. Better company.</span></div><div className="experience-copy"><p className="eyebrow">More than a place on a map</p><h2>The best stories<br />start with<br /><span>“come on in.”</span></h2><p>Local people bring a destination to life. Trafalgar's Be My Guest experiences connect travelers with hosts who share their food, homes, and stories.</p><a className="text-link" href="https://www.trafalgar.com/real-word/be-my-guest-local-travel-experience/" target="_blank" rel="noreferrer">Read about Be My Guest on Trafalgar.com <ArrowUpRight size={17} /></a></div></section>
  <section className="public-section difference" id="difference"><Heading eyebrow="Room to enjoy the journey" title="Less planning. More being there." /><div className="difference-grid">{[[Compass,"A local perspective","See the landmarks, then discover the streets, stories, and small moments around them."],[Users,"Shared discoveries","Travel with people who are just as curious about the world as you are."],[Heart,"Time for what matters","An inviting itinerary leaves more room for conversation, connection, and discovery."]].map(([Icon,title,text]) => <div key={title}><span className="feature-icon"><Icon /></span><h3>{title}</h3><p>{text}</p></div>)}</div></section>
  <section className="closing-banner"><div><p className="eyebrow">Make room for somewhere new</p><h2>Your next story is waiting.</h2></div><a href="#destinations" className="action white">Explore destinations <ArrowRight size={18} /></a></section></main><footer className="public-footer"><Logo /><p>Independent design concept for review.<br />Sample journeys; no bookings or payments are processed here.</p><button className="text-link" onClick={() => go("traveler")}>Explore the traveler view <ArrowUpRight size={16} /></button></footer></div>;
}

function Stat({ icon: Icon, label, value, foot, red = false }) { return <div className={`stat ${red ? "stat-red" : ""}`}><div className="stat-label">{label}<Icon size={19} /></div><strong>{value}</strong><p>{foot}</p></div>; }

function TravelerOverview({ setPage, openTrip, checks, setChecks }) {
  return <><Heading eyebrow="Your travel journal" title="Hello, Alex. Where to next?" text="A little less planning. A lot more looking forward." action={<Action secondary onClick={() => setPage("My journeys")}>My journeys <ArrowRight size={16} /></Action>} /><div className="traveler-hero"><div className="traveler-hero-copy"><span className="light-tag"><span /> Your next adventure</span><h2>Italy is calling.</h2><p>Ten days of art, coastal villages, and<br className="desktop-break" /> the kind of meals you remember.</p><button className="action white" onClick={() => openTrip(TRIPS[0])}>View my itinerary <ArrowRight size={17} /></button></div><Photo trip={TRIPS[0]} eager /><div className="journey-ticket"><span><CalendarDays size={19} /><strong>12 October</strong><small>Departure date</small></span><span><MapPin size={19} /><strong>Rome, Italy</strong><small>Where it begins</small></span><span><Users size={19} /><strong>2 travelers</strong><small>You & your travel companion</small></span><Badge>Confirmed</Badge></div></div><div className="traveler-columns"><section className="panel"><Heading title="Get ready for your journey" action={<span className="muted small">{checks.filter(Boolean).length} of 4 ready</span>} /><div className="preparation-progress"><span style={{ width: `${checks.filter(Boolean).length * 25}%` }} /></div>{["Review your travel documents", "Add your arrival details", "Share dietary preferences", "Read your destination guide"].map((item,i) => <label className={`check-row ${checks[i] ? "complete" : ""}`} key={item}><input type="checkbox" checked={checks[i]} onChange={() => setChecks(checks.map((v,j) => j === i ? !v : v))} /><span>{item}</span>{checks[i] ? <span className="small muted">Ready</span> : <ChevronRight size={16} />}</label>)}</section><section className="panel packing-card"><span className="feature-icon"><Sparkles /></span><p className="eyebrow">A little inspiration</p><h3>Pack light.<br />Come home with stories.</h3><p className="muted">Comfortable shoes, a curious mind, and a little room in your bag for something unexpected.</p><button className="text-link" onClick={() => setPage("Help & support")}>See travel tips <ArrowRight size={16} /></button></section></div><div className="dashboard-stats"><Stat label="Upcoming journeys" value="2" icon={Map} foot="Italy & Japan are on the horizon" /><Stat label="Next departure" value="12 Oct" icon={CalendarDays} foot="Your Italian adventure begins" /><Stat label="Travel checklist" value={`${checks.filter(Boolean).length}/4`} icon={CheckCircle2} foot="Small steps. Smoother travels." /></div></>;
}

function AdminOverview({ travelers, setPage, openPerson }) {
  const confirmations = travelers.filter(t => t.status === "Confirmed").length;
  return <><Heading eyebrow="A clearer view of every journey" title="Good morning, Taylor." text="Here's what's happening across your travel community." action={<Action onClick={() => setPage("Travelers")}>Manage travelers <ArrowRight size={16} /></Action>} /><div className="dashboard-stats admin-stats"><Stat label="Travelers" value={travelers.length} icon={Users} foot="Across this sample workspace" /><Stat label="Journeys in catalog" value={TRIPS.length} icon={Compass} foot="Four regions to discover" /><Stat label="Confirmed travelers" value={confirmations} icon={CheckCircle2} foot="Ready for their next chapter" /><Stat label="Open enquiries" value="3" icon={MessageCircle} foot="Your team can take a look" red /></div><div className="admin-columns"><section className="panel"><Heading title="Upcoming departures" action={<button className="text-link" onClick={() => setPage("Journey catalog")}>View catalog <ArrowRight size={15} /></button>} />{TRIPS.slice(0,3).map(trip => <div className="departure-row" key={trip.id}><Photo trip={trip} /><div><h3>{trip.place}</h3><p>{trip.date}</p></div><Badge>{trip.status === "Available" ? "Planning" : trip.status}</Badge></div>)}</section><section className="panel attention-panel"><p className="eyebrow">Keep the journey moving</p><h3>A personal touch<br />makes the difference.</h3><p>There are three sample enquiries ready for your team's attention.</p><Action onClick={() => setPage("Enquiries")}>Review enquiries <ArrowRight size={16} /></Action><div className="team-avatars"><span>TB</span><span>AQ</span><span>ML</span><small>Your guest experience team</small></div></section></div><section className="panel"><Heading title="Your travel community" action={<button className="text-link" onClick={() => setPage("Travelers")}>All travelers <ArrowRight size={15} /></button>} /><TravelerTable travelers={travelers.slice(0,4)} openPerson={openPerson} /></section></>;
}

function TravelerTable({ travelers, openPerson }) { return <div className="table-scroll"><table><thead><tr><th>Traveler</th><th>Destination</th><th>Status</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{travelers.map(person => <tr key={person.email}><td><div className="person"><span className="avatar">{person.initials}</span><div><strong>{person.name}</strong><small>{person.email}</small></div></div></td><td><span className="inline-icon"><MapPin size={14} />{person.trip}</span></td><td><Badge>{person.status}</Badge></td><td><button className="icon-button" aria-label={`View ${person.name}`} onClick={() => openPerson(person)}><ArrowUpRight size={18} /></button></td></tr>)}</tbody></table>{!travelers.length && <div className="empty-state"><Search /><p>No travelers match this search.</p></div>}</div>; }

function AccountSettings({ notify }) {
  return <><Heading eyebrow="Make yourself at home" title="Profile & preferences" text="Personal details and thoughtful touches for a smoother journey." /><form className="panel profile-form" onSubmit={e => { e.preventDefault(); notify("Preview preferences saved for this visit."); }}><div className="profile-intro"><span className="avatar large">AM</span><div><h3>Alex Morgan</h3><p className="muted">Sample traveler profile</p></div></div><div className="form-grid"><label>First name<input defaultValue="Alex" required /></label><label>Last name<input defaultValue="Morgan" required /></label><label>Email address<input defaultValue="alex@example.com" type="email" required /></label><label>Preferred language<select defaultValue="English"><option>English</option><option>French</option><option>Spanish</option></select></label><label className="full-width">Travel preferences<textarea defaultValue="Local food, art galleries, and a room with a view." rows="3" /></label></div><div className="form-footer"><p className="muted small">Preview only. No account records are updated.</p><Action type="submit">Save preferences <Check size={16} /></Action></div></form></>;
}

function HelpPage() { return <><Heading eyebrow="Here for the little questions, too" title="A helping hand for your journey." text="Useful answers before you set off." /><section className="panel faq">{[["What should I pack?","Comfortable walking shoes, layers suited to the season, any personal medication, and copies of your travel documents are a useful starting point. Check the details for your actual itinerary before departing."],["Where can I find my itinerary?","In this preview, choose My journeys and open a destination card to explore a sample itinerary."],["Can I save destinations for later?","Yes. Tap the heart on a destination card. Your selection appears in Saved places during this preview session."],["Are these actual bookings?","No. All travelers, dates, and journeys in this workspace are sample content for reviewing the interface. No real bookings or payments are created."]].map(([q,a]) => <details key={q}><summary>{q}<Plus size={18} /></summary><p>{a}</p></details>)}</section></>; }

function Workspace({ role, page, setPage, go, saved, toggleSave, openTrip, travelers, setTravelers, notify, openPerson, checks, setChecks }) {
  const [drawer, setDrawer] = useState(false);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("All statuses");
  const [addPerson, setAddPerson] = useState(false);
  const [team, setTeam] = useState(INITIAL_TEAM);
  const [addTeam, setAddTeam] = useState(false);
  const [expandedEnquiry, setExpandedEnquiry] = useState(null);
  const isTraveler = role === "traveler";
  useEffect(() => { setSearch(""); setStatus("All statuses"); setDrawer(false); }, [page,role]);
  const selectPage = item => { setPage(item); setDrawer(false); window.scrollTo(0,0); };
  const nav = <><div className="sidebar-brand"><Logo /><span>{isTraveler ? "Your world of travel" : "The travel workspace"}</span></div><p className="nav-caption">{isTraveler ? "My travel" : role === "admin" ? "Administration" : "Team workspace"}</p><nav aria-label={`${role} navigation`}>{NAVS[role].map(([label,Icon]) => <button key={label} className={page === label ? "active" : ""} onClick={() => selectPage(label)} aria-current={page === label ? "page" : undefined}><Icon size={19} /><span>{label}</span>{label === "Enquiries" && <small>3</small>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-note"><Globe2 size={22} /><strong>Good journeys start<br />with good people.</strong></div><button className="person sidebar-person" onClick={() => selectPage(isTraveler ? "Profile" : "Settings")}><span className="avatar">{isTraveler ? "AM" : "TB"}</span><span><strong>{isTraveler ? "Alex Morgan" : "Taylor Brooks"}</strong><small>{isTraveler ? "Traveler" : role === "admin" ? "Administrator" : "Travel manager"}</small></span><ChevronDown size={15} /></button></div></>;
  let content;
  if (page === "Overview") content = isTraveler ? <TravelerOverview setPage={selectPage} openTrip={openTrip} checks={checks} setChecks={setChecks} /> : <AdminOverview travelers={travelers} setPage={selectPage} openPerson={openPerson} />;
  else if (["My journeys","Saved places","Journey catalog"].includes(page)) {
    const list = (page === "My journeys" ? TRIPS.slice(0,2) : page === "Saved places" ? TRIPS.filter(t => saved.includes(t.id)) : TRIPS).filter(t => `${t.name} ${t.place}`.toLowerCase().includes(search.toLowerCase()));
    content = <><Heading eyebrow="The places you'll remember" title={page} text={page === "Saved places" ? "Keep a little inspiration close at hand." : "Discover the details. Look forward to every moment."} /><div className="list-toolbar"><label className="search-field"><Search size={18} /><input aria-label="Search journeys" placeholder="Search journeys or destinations" value={search} onChange={e => setSearch(e.target.value)} /></label><span className="muted small">{list.length} journeys</span></div><div className="destination-grid workspace-trips">{list.map(trip => <TripCard key={trip.id} trip={trip} saved={saved.includes(trip.id)} onSave={toggleSave} onOpen={openTrip} />)}</div>{!list.length && <div className="panel empty-state"><Heart /><h3>{page === "Saved places" ? "Your next adventure belongs here." : "No journeys found."}</h3><p className="muted">{page === "Saved places" ? "Save a destination using its heart button to see it here." : "Try a different destination."}</p><Action secondary onClick={() => page === "Saved places" ? selectPage("My journeys") : setSearch("")}>{page === "Saved places" ? "Browse my journeys" : "Clear search"}</Action></div>}</>;
  } else if (page === "Travelers") {
    const filtered = travelers.filter(t => `${t.name} ${t.email} ${t.trip}`.toLowerCase().includes(search.toLowerCase()) && (status === "All statuses" || t.status === status));
    content = <><Heading eyebrow="People at the heart of every journey" title="Your travelers" text="A thoughtful experience starts with knowing your guests." action={<Action onClick={() => setAddPerson(true)}><Plus size={17} /> Add sample traveler</Action>} /><section className="panel"><div className="list-toolbar"><label className="search-field"><Search size={18} /><input aria-label="Search travelers" placeholder="Search by name, email, or destination" value={search} onChange={e => setSearch(e.target.value)} /></label><label className="filter-select"><SlidersHorizontal size={15} /><select aria-label="Traveler status" value={status} onChange={e => setStatus(e.target.value)}><option>All statuses</option><option>Confirmed</option><option>Planning</option></select></label></div><TravelerTable travelers={filtered} openPerson={openPerson} /><p className="table-footer">Showing {filtered.length} of {travelers.length} sample travelers</p></section></>;
  } else if (page === "Enquiries") content = <><Heading eyebrow="Every question deserves a little care" title="Guest enquiries" text="Sample conversations for the guest experience team." /><section className="panel enquiries">{[["Jamie Chen","Arrival arrangements","Could you help me understand where the Japan journey begins?","JC"],["Alex Morgan","Dietary preferences","I'd like to add a vegetarian meal preference to my itinerary.","AM"],["Jordan Ellis","Travel documents","Where can I find the documents for my upcoming journey?","JE"]].map(([name,subject,message,initials],i) => <article key={name}><button onClick={() => setExpandedEnquiry(expandedEnquiry === i ? null : i)} aria-expanded={expandedEnquiry === i}><span className="avatar">{initials}</span><span><strong>{subject}</strong><small>{name} · Sample enquiry</small></span><Badge>Open</Badge><ChevronDown size={17} /></button>{expandedEnquiry === i && <div className="enquiry-message"><p>{message}</p><span className="small muted">Conversation preview only. No message is sent.</span></div>}</article>)}</section></>;
  else if (page === "Team") content = <><Heading eyebrow="Great travel is a team effort" title="Your people" text="Meet the sample team behind the guest experience." action={<Action onClick={() => setAddTeam(true)}><Plus size={16} /> Add sample teammate</Action>} /><div className="team-grid">{team.map((member,i) => <section className="panel team-card" key={`${member.name}-${i}`}><span className="avatar large">{member.initials}</span><h3>{member.name}</h3><p className="muted">{member.job}</p><Badge>Active</Badge></section>)}</div></>;
  else if (page === "Payments") content = <><Heading eyebrow="All the details, in one place" title="Payment history" text="Sample booking records for this design preview." /><section className="panel"><div className="inline-notice"><ShieldCheck size={19} /> These are fictional records. This preview cannot accept or transfer money.</div><div className="table-scroll"><table><thead><tr><th>Journey</th><th>Reference</th><th>Amount</th><th>Status</th></tr></thead><tbody><tr><td>Italy · Booking deposit</td><td>EXAMPLE-001</td><td>$250.00</td><td><Badge>Paid</Badge></td></tr><tr><td>Japan · Reservation deposit</td><td>EXAMPLE-002</td><td>$200.00</td><td><Badge>Paid</Badge></td></tr></tbody></table></div><p className="table-footer">Sample amounts are not prices or offers from Trafalgar.</p></section></>;
  else if (page === "Help & support") content = <HelpPage />;
  else content = <AccountSettings notify={notify} />;
  const addForm = (isTeam) => <Dialog title={isTeam ? "Add a sample teammate" : "Add a sample traveler"} close={() => { setAddPerson(false); setAddTeam(false); }}><form className="dialog-form" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); const name = String(data.get("name")).trim(); if (!name) return; const initials = name.split(/\s+/).slice(0,2).map(s => s[0]).join("").toUpperCase(); if(isTeam) setTeam([...team,{name,initials,job:String(data.get("job"))}]); else { const email = String(data.get("email")).trim().toLowerCase(); if (travelers.some(p => p.email.toLowerCase() === email)) { notify("That email is already in the sample list."); return; } setTravelers([...travelers,{name,initials,email,trip:String(data.get("trip")),status:"Planning"}]); } setAddPerson(false); setAddTeam(false); notify("Sample record added for this preview only."); }}><p className="muted">Use fictional details. Changes stay in memory and disappear when you reload.</p><label>Full name<input name="name" required placeholder="e.g. Riley Jordan" maxLength="70" /></label>{isTeam ? <label>Role<select name="job"><option>Travel manager</option><option>Guest experience</option></select></label> : <><label>Email<input name="email" type="email" required placeholder="riley@example.com" /></label><label>Destination<select name="trip">{TRIPS.map(t => <option key={t.id}>{t.place}</option>)}</select></label></>}<Action type="submit"><Plus size={16} /> Add to preview</Action></form></Dialog>;
  return <div className="workspace"><aside className="sidebar">{nav}</aside>{drawer && <div className="mobile-drawer"><button className="drawer-backdrop" aria-label="Close navigation" onClick={() => setDrawer(false)} /><aside>{nav}<button className="icon-button close-drawer" onClick={() => setDrawer(false)} aria-label="Close navigation"><X /></button></aside></div>}<div className="workspace-main"><header className="workspace-top"><button className="icon-button mobile-toggle" onClick={() => setDrawer(true)} aria-label="Open workspace navigation"><Menu /></button><div className="breadcrumb">{isTraveler ? "My travel" : role === "admin" ? "Workspace" : "My team"}<ChevronRight size={14} /><strong>{page}</strong></div><div className="top-tools"><button className="text-link" onClick={() => go("home")}>View website <ArrowUpRight size={15} /></button><button className="icon-button notification" aria-label="Notifications" onClick={() => notify("You're all caught up. This is a sample workspace.")}><Bell size={19} /><span /></button><span className="avatar small-avatar">{isTraveler ? "AM" : "TB"}</span></div></header><main className="workspace-content" key={`${role}-${page}`}>{content}<footer className="workspace-footer"><span>Trafalgar-inspired design preview</span><span><ShieldCheck size={13} /> Sample data · No live transactions</span></footer></main></div>{addPerson && addForm(false)}{addTeam && addForm(true)}</div>;
}

function PreviewApp() {
  const [view, setView] = useState("home");
  const [page, setPage] = useState("Overview");
  const [saved, setSaved] = useState([2,3,4]);
  const [travelers, setTravelers] = useState(INITIAL_TRAVELERS);
  const [checks, setChecks] = useState([true,false,false,true]);
  const [trip, setTrip] = useState(null);
  const [person, setPerson] = useState(null);
  const [toast, setToast] = useState("");
  useEffect(() => { if(!toast) return; const timer = setTimeout(() => setToast(""),3500); return () => clearTimeout(timer); },[toast]);
  const go = next => { setView(next); setPage("Overview"); window.scrollTo(0,0); };
  const toggleSave = id => setSaved(current => current.includes(id) ? current.filter(v => v !== id) : [...current,id]);
  return <><div className="review-bar"><span className="review-label"><span className="review-dot" /> Design preview <span className="review-detail">/ sample content</span></span><div className="view-switch" aria-label="Preview screen">{[["home","Website"],["traveler","Traveler"],["admin","Admin"],["manager","Manager"]].map(([value,label]) => <button key={value} onClick={() => go(value)} className={view === value ? "active" : ""} aria-pressed={view === value}>{label}</button>)}</div><span className="review-end">Local review only</span></div>{view === "home" ? <PublicHome go={go} saved={saved} toggleSave={toggleSave} openTrip={setTrip} /> : <Workspace role={view} page={page} setPage={setPage} go={go} saved={saved} toggleSave={toggleSave} openTrip={setTrip} travelers={travelers} setTravelers={setTravelers} notify={setToast} openPerson={setPerson} checks={checks} setChecks={setChecks} />}{trip && <Dialog title={trip.name} close={() => setTrip(null)}><Photo trip={trip} className="dialog-photo" /><div className="dialog-body"><p className="eyebrow">{trip.place} · {trip.days} days · Illustrative itinerary</p><p>{trip.description}</p><div className="itinerary">{trip.route.split(" · ").map((stop,i) => <div key={stop}><span>{i+1}</span><div><strong>{stop}</strong><p className="muted">{["Arrive, settle in, and explore.","Make time for local stories and discoveries.","Enjoy a final perspective on your journey."][i]}</p></div></div>)}</div><Action secondary onClick={() => toggleSave(trip.id)}><Heart size={16} fill={saved.includes(trip.id) ? "currentColor" : "none"} />{saved.includes(trip.id) ? "Saved to your places" : "Save this destination"}</Action><p className="muted small">Sample itinerary for design review, not a bookable Trafalgar tour.</p></div></Dialog>}{person && <Dialog title="Traveler details" close={() => setPerson(null)}><div className="dialog-body"><div className="person"><span className="avatar large">{person.initials}</span><div><h3>{person.name}</h3><p className="muted">{person.email}</p></div></div><dl className="detail-list"><div><dt>Destination</dt><dd>{person.trip}</dd></div><div><dt>Status</dt><dd><Badge>{person.status}</Badge></dd></div><div><dt>Record type</dt><dd>Fictional preview traveler</dd></div></dl></div></Dialog>}{toast && <div className="toast" role="status"><CheckCircle2 size={18} />{toast}<button aria-label="Dismiss notification" onClick={() => setToast("")}><X size={16} /></button></div>}</>;
}

createRoot(document.getElementById("root")).render(<React.StrictMode><PreviewApp /></React.StrictMode>);
